name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: corepack enable
      - name: Install uv
        run: pip install uv
      - name: Set up uv virtual environment
        run: uv venv
      - name: Install backend dependencies
        run: uv pip install -e backend[test]
      - name: Install frontend dependencies
        run: cd frontend && pnpm install
      - name: Run tests
        run: make test
